apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mc
  template:
    metadata:
      labels:
        name: mc
    spec:
      containers:
        - name: mc
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["/bin/bash", "-c", "while true; do sleep 30; done;"]
          volumeMounts:
          {{ range $path, $bytes := .Files.Glob ( printf "scripts/**") -}}
          - name: scripts
            mountPath: {{ printf "/mc/%s" $path | indent 14 }}
            subPath: {{ sha256sum $path | indent 14 }}
          {{ end }}
      volumes:
        - name: scripts
          configMap:
            name: {{ .Release.Name }}-scripts
            defaultMode: 0755
